In [ ]:
#installation
pip install numpy

In [ ]:
#checking the version
import numpy as np
print(np.__version__)

2.1.3


In [ ]:
#array
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [ ]:
#array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#zero
import numpy as np
arr=np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#zeros
import numpy as np
arr=np.zeros((10,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#ones
import numpy as np
arr=np.ones((5,7))
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
arr=np.full((4,7),9)
arr

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [ ]:
arr=np.empty((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr=np.arange(1,100)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [ ]:
arr=np.arange(2,100,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


In [ ]:
arr=np.arange(1,99,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97])

In [ ]:
import numpy as np
arr=np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
arr=np.linspace(1,20,7)
arr

array([ 1.        ,  4.16666667,  7.33333333, 10.5       , 13.66666667,
       16.83333333, 20.        ])

In [ ]:
#random variable only for positive numbers
import numpy as np
arr=np.random.rand(10)
arr

array([0.16686023, 0.0476092 , 0.36868516, 0.02657372, 0.97063233,
       0.25316649, 0.18980349, 0.44881521, 0.15242522, 0.32107034])

In [ ]:
#random variable only for negative numbers
import numpy as np
arr=np.random.randn(10)
arr

array([-0.78415309,  0.50191193,  0.38969896, -1.36153704,  0.08534315,
        0.74875751, -0.46617451, -1.19530015,  0.76794948,  0.809921  ])

In [ ]:
#this prints single output
import numpy as np
arr=np.random.randint(10)
arr

1

In [ ]:
import numpy as np
arr=np.random.random_integers(10)
arr

/tmp/ipykernel_631/3813325485.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  arr=np.random.random_integers(10)


np.int64(6)

In [ ]:
import numpy as np
colours=["red","green","orange","blue","white","pink","black","grey"]
print(np.random.choice(colours,3))

['red' 'grey' 'blue']


In [ ]:
#copy value doesn't take any address
import numpy as np
arr=np.array([1,2,3])

new=arr.copy()
new[1]=100
print("array value is:",arr)
print("copies value is:",new)

array value is: [1 2 3]
copies value is: [  1 100   3]


In [ ]:
#view-it access values and address
import numpy as np
arr=np.array([1,2,3])

new=arr.view()
new[1]=100
print("array value is:",arr)
print("viewed value is:",new)

array value is: [  1 100   3]
viewed value is: [  1 100   3]


In [ ]:
arr=np.array([5,10,15,20,25,30])
arr+=10
print("updated array value is:",arr)

updated array value is: [15 20 25 30 35 40]


In [ ]:
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.add(A,B))

[ 7  9 11 13 15]


In [ ]:
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.multiply(A,B))

[ 6 14 24 36 50]


In [ ]:
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.subtract(A,B))

[-5 -5 -5 -5 -5]


In [ ]:
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.divide(A,B))

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
#dot-it multiplication of  the A and B elements and add the answers of the multiply
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.dot(A,B))


130


In [ ]:
Arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(sum(Arr))

55


In [ ]:
Arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(max(Arr))

10


In [ ]:
Arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(min(Arr))

1


In [ ]:
Arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.std(Arr))

2.8722813232690143


In [ ]:
Arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.var(Arr))

8.25


In [ ]:
Arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.sqrt(Arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [ ]:
import numpy as np
arr=np.array([9,4,7,3,8,9,4,1,11,141,34])

print(np.sort(arr))

[  1   3   4   4   7   8   9   9  11  34 141]


In [ ]:
#un1que-dont show the duplicate elements
import numpy as np
arr=np.array([9,4,7,3,8,9,4,1,11,141,34])

print(np.unique(arr))

[  1   3   4   7   8   9  11  34 141]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])

print(arr.shape)

(9,)


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])

print(arr.size)

9


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])

print(arr.itemsize)

8


In [ ]:
#ndim-no of dimenesion
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])

print(arr.ndim)

1


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])

print(arr.dtype)

int64


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)

(2, 4)


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])

print(arr.ndim)

2


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])

print(arr[0,1])

2


In [ ]:
#:,1-this one gives the output as a 1st index of both columns
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])

print(arr[:,1])

[2 6]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5,6,7,8,99,10,11,12,13,14,15]])

print("original array",arr)
new=arr.reshape(5,3)
print(new)

original array [[ 1  2  3  4  5  6  7  8 99 10 11 12 13 14 15]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 99]
 [10 11 12]
 [13 14 15]]
